### ISSUE TITLE
Bookmarks manager disponibility not working

### ISSUE THREAD

**Issue by Useless-Panda** [Gerardufoin/FreeKiss#2]
Bookmarks manager disponibility is not working when i click on + (plus) button it just keeps loading it's not working on  Frontpage, Mangas or Chapters page I'm using waterfox portable 56.2.8 (latest Version)

P.S  thanks for the Firefox veriosn

**Comment by Gerardufoin** [comment]
Hey !

I tested on both Waterfox and Waterfox Portable (56.2.8) and the add button worked as intended.
Are you logged in on KissManga ? The Add buttons will be shown even when logged off, but will do nothing (the managers use the bookmarks of your Kissmanga account to work).

I should probably hide the managers when the user is not connected, that's not really intuitive. I'll do it when I have a bit of time.

Do tell me if that was the issue. Otherwise, if you have checked you are logged in and nothing at all happens when you click the add buttons, try sending me a link to the website where you downloaded your version of Waterfox Portable.

Have a nice day!

**Comment by Assassin143** [comment]
Hi Thanks for your reply it was works on fresh install of waterfox but after a while it just stops working i downloaded waterfox from the official site

**Comment by Useless-Panda** [comment]
hi thanks for your reply it works on freash install of waterfox but after a while it stops working i downloaded waterfox from official site

**Comment by Useless-Panda** [comment]
after trying different things for a while i installed fresh waterfox and i found out what's causing this problem when i install Self Destruct Cookies then freekiss stops working and 2nd problem is when i use freekiss+KissAnime Anti-Adblock Blocker kissamanga's Latest update tab on frontpage stops scrolling
can u please make it work with KissAnime Anti-Adblock Blocker

**Comment by Gerardufoin** [comment]
Hi again ! Didn't think about the conflict with other extensions, glad you managed to figure out the source of the problem.

I'll try to look into it and fix the conflict as soon as possible. I am currently moving, so my disponibility is a bit all over the place, so you'll have to be a bit patient ^^'

I'll keep you updated when it's done.

**Comment by Useless-Panda** [comment]
o.k no problem i just want to inform you that there are two other conflicts that i encountered 1. if i disable third party cookies then it stops working 2. it had a conflict with agent switcher addon which i changed and it started working again. 

P.S Good Luck with your moving

**Comment by Gerardufoin** [comment]
Thanks!

Can you give me the list of your addons? It'll be faster to check if everything is working that way. You can send them via email if you don't want to list them on Github (gdfprojects@gmail.com)

**Comment by Assassin143** [comment]
I had trouble with these two extensions
1.Self-Destructing Cookie which i replaced with [Cookie-AutoDelete] (https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)
2.[User-Agent Switcher and Manager] (https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) Which i replaced with [Random Agent Spoofer] (https://github.com/dillbyrne/random-agent-spoofer)

**Comment by Useless-Panda** [comment]
I had trouble with these two extensions
1.[Self-Destructing Cookie](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-webex) which i replaced with [Cookie-AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)
2.[User-Agent Switcher and Manager](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) Which i replaced with [Random Agent Spoofer](https://github.com/dillbyrne/random-agent-spoofer)
after that Freekiss started working again
and the other problem that i found was with the setting of **third-party cookies** when set to **never** it stopped working after changing it to **from visited** it started working again

**Comment by Gerardufoin** [comment]
Hey, sorry I took so long to get back to you.

I don't know if you are still using FreeKiss or not, but I investigated what you reported me:

1. I installed Self-Destructing Cookie but everything seems to work fine. What was your issue when using it ?
2. User-Agent Switcher on Waterfox seems to be messing around with my ajax requests which are then intercepted by the Cloudflare of KissManga. There is sadly not much I can do, the issue is on their end :/
3. The Third-Party Cookies problem is a bit similar that with User-Agent Switcher. The extension needs the sessionID of KissManga (stored in a cookie) to not be considered as crossdomain and rejected by the Cloudflare of KissManga. It seemed like browsers like Chrome and Firefox took this into consideration when creating the Third Party Cookies setting, but Waterfox didn't, which makes my ajax requests rejected by KissManga's firewall if the cookie is not here.

Sorry to not have any good news for you :/ If Waterfox updates follow those of Firefox, those issues should resolve themselves at some point, but right now there is not much I can do.

**Comment by Useless-Panda** [comment]
Thanks for looking into it.
i'm still using freekiss i was able to resolve my issues by changing browser setting and extensions.

~~can u please also look into KissAnime Anti-Adblock Blocker when both enabled it breaks front page's  Latest update tab's scrolling~~

It Stared Working after they updated their script.
